---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
 
 
    - name: Provision a EC2 Instance
      ec2:
         key_name: essentialsKeypair 
         region: us-east-1 
         instance_type: t2.micro
         image: ami-6871a115
         wait: yes
         wait_timeout: 500
         count: 1
         monitoring: no
         vpc_subnet_id: subnet-65d5932d 
         assign_public_ip: yes
         group_id: sg-9dec81ec 
      register: ec2_out
 
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ec2_out.instances}}'
